### ISSUE TITLE
we should use dune

### ISSUE THREAD

**Issue by UnixJunkie** [rdicosmo/parmap#40]

**Comment by UnixJunkie** [comment]
the need would disappear if we use jbuilder, which generates them automatically

**Comment by rdicosmo** [comment]
I have nothing against experimenting a new build system: feel free to create a
branch and play with it. If it turns out to be stable across all the platforms,
we'll go for it

On Sun, Feb 18, 2018 at 06:27:41PM -0800, Francois BERENGER wrote:
> the need would disappear if we use jbuilder, which generates them automatically
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Roberto Di Cosmo
 
------------------------------------------------------------------
Computer Science Professor
            (on leave at INRIA from IRIF/University Paris Diderot)

Software Heritage             E-mail : roberto@dicosmo.org        
INRIA			         Web : http://www.dicosmo.org     
Bureau C123		     Twitter : http://twitter.com/rdicosmo
2, Rue Simone Iff                Tel : +33 1 80 49 44 42
CS 42112
75589 Paris Cedex 12
------------------------------------------------------------------                                                 
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Comment by UnixJunkie** [comment]
@rgrinberg if anyone is looking for a famous OCaml project to do some dune evangelization... ;)

**Comment by UnixJunkie** [comment]
this is more annoying/difficult than I thought

**Comment by olafhering** [comment]
A first attempt can be found in https://github.com/olafhering/parmap/tree/dune-wip
